<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '7595f3aaa72fc24e26b7288528cec88c',
  'DATABASE_URL' => 'mysql://romainbre:27a0639b0267e3fcc7a3f8265009d9d2@db.3wa.io/romainbre_pronosite?serverVersion=5.7',
);
